server:
  port: 8002

spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

app:
  jwt:
    secret-key: fCaMV7vFnbGpznEVUxXW
