server:
  port: 8005
  error:
    include-message: always

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_order
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 20000
      idle-timeout: 20000
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
  jackson:
    time-zone: GMT+7
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

app:
  jwt:
    secret-key: fCaMV7vFnbGpznEVUxXW
kafka:
  topics:
    orderCreated: topic-orderCreated
